name: VPN Monster Auto-Update

on:
  push:
    paths:
      - 'all_sources.txt'
      - 'parser.py'
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # КРИТИЧЕСКИ ВАЖНО: разрешает боту сохранять файлы
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run Parser
        run: python parser.py

      - name: Commit and Push changes
        run: |
          git config --local user.email "bot@github.com"
          git config --local user.name "VPN-Monster-Bot"
          git add *.txt
          git commit -m "Auto-Update: $(date)" || echo "No changes"
          git push
